---
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install core packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ ubuntu_core_packages }}"
