# inventories/development/hosts.yml

all:
  children:
    windows:
      hosts:
        win-dev.local:
          ansible_user: admin  # Username to connect to the Windows machine
          ansible_connection: winrm  # Use WinRM for remote management
          ansible_port: 5986  # HTTPS port (default for secure WinRM)
          ansible_winrm_transport: certificate  # 🛡️ Use certificate-based authentication
          ansible_winrm_cert_pem: "~/.certs/winrm_client_cert.pem"  # 📜 Client cert (public)
          ansible_winrm_cert_key_pem: "~/.certs/winrm_client_key.pem"  # 🔑 Client cert (private key)
          ansible_winrm_server_cert_validation: ignore  # ❗ For dev only! Set to 'validate' in staging/prod

    macos:
      hosts:
        mac-dev.local:
          ansible_user: mac-dev  # Local user account on macOS
          ansible_connection: ssh  # SSH is default for Unix-like systems

    ubuntu:
      hosts:
        ubuntu-dev.local:
          ansible_user: ubuntu  # Default Ubuntu SSH user
          ansible_connection: ssh

    arch:
      hosts:
        arch-dev.local:
          ansible_user: arch-dev  # Username for Arch-based system
          ansible_connection: ssh

    wsl:
      hosts:
        wsl-dev:
          ansible_connection: local  # Run tasks locally inside WSL environment
