# inventories/development/hosts.yml
all:
  children:
    linux:
      children:
        ubuntu:
          hosts:
            ubuntu-dev-01:
              ansible_host: 192.168.1.10
              ansible_user: devuser
              ansible_python_interpreter: /usr/bin/python3
        arch:
          hosts:
            arch-dev-01:
              ansible_host: 192.168.1.11
              ansible_user: devuser
              ansible_python_interpreter: /usr/bin/python3

    darwin:
      hosts:
        macbook-dev-01:
          ansible_connection: local
          ansible_user: binahf
          ansible_python_interpreter: /opt/homebrew/bin/python3

    windows:
      hosts:
        windows-dev-01:
          ansible_host: 192.168.1.12
          ansible_user: DevAdmin
          ansible_password: "{{ vault_windows_password }}"
          ansible_port: 5986
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore

    wsl:
      hosts:
        wsl-ubuntu:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
