# ansible/inventories/staging/hosts.yml
all:
  children:
    ubuntu:
      hosts:
        staging-ubuntu-01:
        staging-ubuntu-02:
    arch:
      hosts:
        staging-arch-01:
    darwin:
      hosts:
        staging-mac-01:
    windows:
      hosts:
        staging-win-01:
    wsl:
      hosts:
        staging-wsl-01:
