---
- name: Configure power settings
  win_power_plan:
    name: High performance

- name: Set timezone
  win_timezone:
    timezone: "{{ system_timezone }}"

- name: Configure Windows updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
    state: installed
  register: update_result
  async: 1800
  poll: 0

- name: Reboot if updates installed
  win_reboot:
  when: update_result.reboot_required
