---
- name: Ensure winget is available
  ansible.windows.win_command: "winget --version"
  register: winget_check
  failed_when: false
  changed_when: false

- name: Use winget to install or upgrade packages
  ansible.windows.win_powershell:
    script: |
      $app = "{{ item.name | default(item) }}"
      try {
        $installed = winget list $app
        if ($installed -like "*No installed package found*") {
          winget install --accept-package-agreements --accept-source-agreements -h -s "winget" $app
        }
        else {
          winget upgrade $app
        }
      } catch {
        Write-Host "Winget failed for $app, skipping"
        exit 1
      }
  loop: "{{ winget_packages }}"
  when: winget_check.rc == 0
  register: winget_result
  failed_when: false
