# ansible/site.yml
---
- name: 🚀 Multi-Platform Provisioning Entry Point
  hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - "config/group_vars/all.yml"
    - "config/group_vars/{{ ansible_os_family | lower }}.yml"
    - "{{ vault_file | default('secrets/ansible-vault/' + ansible_os_family | lower + '.yml') }}"

  pre_tasks:
    - name: "📦 Show detected platform info"
      debug:
        msg: "OS Family: {{ ansible_os_family }}, Distribution: {{ ansible_distribution }}, Kernel: {{ ansible_kernel }}"

  roles:
    - { role: base, tags: ['base'] }

  tasks:
    - name: "🗭 Include Ubuntu playbook"
      ansible.builtin.import_playbook: "playbooks/ubuntu/main.yml"
      when: ansible_distribution == "Ubuntu"

    - name: "🗭 Include Arch playbook"
      ansible.builtin.import_playbook: "playbooks/arch/main.yml"
      when: ansible_distribution == "Archlinux"

    - name: "🗭 Include macOS playbook"
      ansible.builtin.import_playbook: "playbooks/darwin/main.yml"
      when: ansible_system == "Darwin"

    - name: "🗭 Include Windows playbook"
      ansible.builtin.import_playbook: "playbooks/windows/main.yml"
      when: ansible_os_family == "Windows"

    - name: "🗭 Include WSL playbook"
      ansible.builtin.import_playbook: "playbooks/wsl/main.yml"
      when: ansible_kernel | lower is search("microsoft")
